# Generated by Django 5.1.4 on 2025-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_description', models.TextField(max_length=1000)),
                ('recipe_image', models.ImageField(upload_to='recipe_folder')),
            ],
        ),
    ]
